[[plugins]]
repo = "Shougo/deoplete.nvim"
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = "zchee/deoplete-clang"
on_ft = ["c", "h", "cpp", "hpp"]
hook_source = '''
let g:deoplete#sources#clang#libclang_path = "/usr/lib/llvm/6.0.0/lib/libclang.so.1"
let g:deoplete#sources#clang#clang_header = "/usr/include"
'''

[[plugins]]
repo = "zchee/deoplete-jedi"
on_ft = ["py"]

[[plugins]]
repo = "fatih/vim-go"
on_ft = ["go"]
hook_source = '''
let g:go_fmt_command = "/home/kouf/go/bin/goimports"
'''

[[plugins]]
repo = "rust-lang/rust.vim"
on_ft = ["rs"]

[[plugins]]
repo = "zchee/deoplete-zsh"
on_ft = ["sh", "zshrc", "zshenv"]

[[plugins]]
repo = "cohama/lexima.vim"
on_i = 1

[[plugins]]
repo = "posva/vim-vue"
on_ft = ["vue"]

[[plugins]]
repo = "pangloss/vim-javascript"
on_ft = ["js"]

[[plugins]]
repo = "neovimhaskell/haskell-vim"
on_ft = ["hs"]
